require(knitr)
require(markdown)
setwd(".")
knit("run_analysis.Rmd", encoding="ISO8859-1")
markdownToHTML("run_analysis.md", "run_analysis.html")
knit("CodeBook.Rmd", encoding="ISO8859-1")
markdownToHTML("CodeBook.md", "CodeBook.html")